### ISSUE TITLE
Finish Glottolog mapping

### ISSUE THREAD

**Issue by tresoldi** [lexibank/luangthongkumkaren#2]
The current Glottolog mapping is tentative and preliminary. The source gives the name of the villages where material was collected, but it was not possible to quickly map them; consultation with experts might be needed.

**Comment by chrzyki** [comment]
Will check the status of this again.

**Comment by CMUgarte** [comment]
I worked on this confirming the glottocodes already present and adding two ones. So, I'm closing this issue now.
